name: "Synchronise Coverity Scan branches on a weekly basis"

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git checkout --config merge -b coverity-develop origin/develop
          git pull origin coverity-develop	
          git push origin coverity-develop
